AkariGroup/akari_software

setup/ansible/system.yml

Clean unused ansible role

---

internal/akari_rpc_server/setup.py
internal/akira_controller_server/setup.py

Fix required akira-proto ver

---

internal/docker/docker-compose.v1.yml
setup/ansible/group_vars/all.yml
setup/ansible/roles/akira/files/daemon.d/env.sh
setup/ansible/roles/akira/tasks/main.yml
setup/ansible/roles/akira/templates/akira.service.j2
setup/ansible/roles/akira/templates/update-akira.service.j2
setup/ansible/roles/arduino/tasks/main.yml
setup/ansible/roles/common/tasks/main.yml
setup/ansible/roles/docker/tasks/main.yml
setup/ansible/roles/dynamixel/tasks/main.yml

ユーザー名として `akari` を仮定していた部分を修正して、ansible を実行している remote の ユーザー名を使うように変更しました。
connection として local, ssh どちらを使った場合でも動作すると思います。（`-c local` で検証しています）

Allow arbitrary username for hosting akira

---

internal/akira_controller_server/setup.py
sdk/akari_client/setup.py

opencv-python-headlessをopencv-pythonに変更

Change opencv dependency

---

AKARI_MANUAL.desktop
README.md

Fix manual link

---

.github/workflows/python-test.yml
internal/akira_frontend/src/pages/Projects/Create/createFromGit.tsx
internal/akira_frontend/src/pages/Projects/Create/createFromTemplate.tsx

projectを作成する時、特にgit cloneなど時間がかかる場合に待機画面が出ないと不自然なので変更します。

Add busy state control to create project

---

.github/workflows/update-akira-images.yml

Disable update lfs

---

sdk/akari_client/akari_client/joint_manager.py

Fix docstring of joint limits

---

sdk/akari_client/setup.py
sdk/akari_proto/setup.py

Merge #219 First
バージョンを0.3.2に更新

Bump version to 0.3.2

---

sdk/akari_client/setup.py
sdk/akari_proto/setup.py

https://github.com/AkariGroup/akari_software/commit/d9c1cf448ed9da81f44a21649f18b9c849444379
に伴ってSDKのバージョンを更新

Bump version to 0.3.3

---

internal/akira_services/jupyter_lab/Dockerfile

akari_tutorialなどで後入れしているipywidgetをデフォルトでインストールするように変更

Add ipywidgets

---

sdk/akari_client/setup.py
sdk/akari_proto/setup.py

akari-client, akari-protoのバージョンを更新

Bump version to 0.3.4

---

setup/ansible/roles/common/tasks/main.yml

Raspberry pi OS用のライブラリのインストールを追加

Fix dependencies

---

sdk/akari_client/setup.py
sdk/akari_proto/setup.py

Bump version to 0.3.5

---

sdk/akari_client/setup.py
sdk/akari_proto/setup.py

Bump version to 0.3.6

---

sdk/akari_client/setup.py
sdk/akari_proto/setup.py

Merge #239 First
バージョン0.4.0へ更新

Bump version to 0.4.0

---

sdk/akari_client/setup.py
sdk/akari_proto/setup.py

Merge https://github.com/AkariGroup/akari_software/pull/245 first
バージョン0.4.1に更新

Bump version 0.4.1

---

internal/akari_rpc_server/akari_rpc_server/server.py
sdk/akari_client/akari_client/akari_client.py

M5, Dynamixelのどちらかが繋がっていなくても起動するように変更

Fix device connection

---

sdk/akari_client/setup.py
sdk/akari_proto/setup.py

Bumpe version 0.4.2

---

.github/workflows/update-akira-images.yml

update_akira_imagesがtimeoutになるので緩和

Fix timeout

---

sdk/akari_client/setup.py
sdk/akari_proto/setup.py

Bump version to 0.4.3
